#!/bin/bash
# Author: Maxim Kalaev

function die() { echo $* ; exit -1; }
function clear_right() { echo -ne "\e[K"; } # Clear to the right of the cursor

function start_emacs_server() {
    # Starting emacs server unless already running & waiting it
    #  to finish the initializations
    timeout=15
    if emacsclient -e t >/dev/null 2>&1; then
        return 0
    fi

    # Update display when running from screen
    [[ -n "$WINDOW" && -e ~/.sdisplay ]] && source ~/.sdisplay

    #emacs --daemon
    (emacs -fg black -bg wheat &)
    for ((i=1; i <= $timeout; ++i)); do
        echo -ne "Waiting for emacs server to start.. ($i sec elapsed)\r"
        sleep 1
        if emacsclient -e t >/dev/null 2>&1; then
            clear_right
            return 0
        fi
    done

    echo
    return 1
}

if [[ -z "$DISPLAY" ]]; then
    #TODO: use emacsclient -nw --alternate-editor= $@ ?
    die "ERROR: DISPLAY not set"
fi

start_emacs_server || die "Timedout connecting emacs server, exiting."

# Using emacsclient to open all the supplied files with optional
# line numbers in emacs server
for f in "$@"; do
    _re='(.*):([0-9]+)(:.*)?'
    if [[ "$f" =~ $_re ]]
    then
        emacsclient -n +${BASH_REMATCH[2]} ${BASH_REMATCH[1]}
    else
        emacsclient -n $f
    fi
# TODO: add tags suport, like 'vi -t'
# emacsclient -ne '(gtags-goto-tag "invoke_operation" "")'
done
