#!/bin/bash
# Author: Maxim Kalaev

if [[ -z "$DISPLAY" ]]; then
    #TODO: use emacsclient -nw --alternate-editor= $@ ?
    echo ERROR: DISPLAY not set
    exit -1
fi

# Starting emacs server unless already running & waiting it
#  to finish the initializations
if ! emacsclient -e t >/dev/null 2>&1
then
    # Update display when running from screen
    [[ -n "$WINDOW" && -e ~/.sdisplay ]] && source ~/.sdisplay

    #emacs --daemon
    (emacs&)
    for ((i=1; i <= 10; ++i)); do
        echo -ne "Waiting for emacs server to start.. $i\r"
        sleep 1
        if emacsclient -e t >/dev/null 2>&1
	then
            break
        else
            if ((i == 10))
            then
                echo "Couldn't connect emacs server after $i sec, exiting.      "
                exit -1
            fi
        fi
    done
    echo -ne "                                         \r"
fi

# Using emacsclient to open all the supplied files with optional
# line numbers in emacs server
for f in "$@"; do
    _re='(.*):([0-9]+)(:.*)?'
    if [[ "$f" =~ $_re ]]
    then
        emacsclient -n +${BASH_REMATCH[2]} ${BASH_REMATCH[1]}
    else
        emacsclient -n $f
    fi
# TODO: add tags suport, like 'vi -t'
# emacsclient -ne '(gtags-goto-tag "invoke_operation" "")'
done
