#!/bin/bash
# Author: Maxim Kalaev

if [[ "$DISPLAY"x == "x" ]]; then
    echo ERROR: DISPLAY not set, -nw mode is not supported
    exit -1
fi

# Starting emacs server unless already running & waiting it
#  to finish the initializations
if ! emacsclient -e t >/dev/null 2>&1
then
    (emacs&) # Double fork
    for ((i=1; i <= 10; ++i)); do
        echo -ne "Waiting for emacs server to start.. $i\r"
        sleep 1
        if emacsclient -e t >/dev/null 2>&1
	then
            break
        else
            if ((i == 10))
            then
                echo "Couldn't connect emacs server after $i sec, exiting.      "
                exit -1
            fi
        fi
    done
    echo -ne "                                         \r"
fi

# Using emacsclient to open all the supplied files with optional
# line numbers in emacs server
for f in "$@"; do
    if [[ "$f" =~ "(.*):([0-9]+):?" ]]
    then
        emacsclient -n +${BASH_REMATCH[2]} ${BASH_REMATCH[1]}
    else
        emacsclient -n $f
    fi
# TODO: add tags suport, like 'vi -t'
# emacsclient -ne '(gtags-goto-tag "invoke_operation" "")'
done
