#!/bin/sh
if [ -z $1 ] ; then
	echo "Usage: measure_bandwidth <destination host IP>";
	exit;
fi

IPERF=`which iperf`
if [ -z $IPERF ] ; then echo "iperf not installed, exiting"; exit; fi

export PATH=/tmp/:$PATH
ssh -n $1 killall -9 iperf
scp $IPERF $1:/tmp
scp $0 $1:/tmp/
ssh -n $1 /tmp/iperf -s -p 1234 -w 2M -l 2M -m > /dev/null &
sleep 1
#sudo iperf -c $1 -p 1234 -w 2M -P 8 -m
#iperf -c $1 -p 1234 -w 2M -P 8 -m -l 2M -t 30 -i 5 -r
iperf -c $1 -p 1234 -w 2M -m -l 2M -t 30 -i 5 -r
ssh $1 killall iperf
