#!/bin/bash 

function ABORT() {
    echo -e '\e[1;31m\nAborting: '$*'\e[0m'
    exit -1
}

function INFO() {
    echo -e '\e[1;32m'$*'\e[0m'
}

function check_environment() {
    which rpm > /dev/null || ABORT "'rpm' tool was not found"
    which rpm2cpio > /dev/null || ABORT "'rpm2cpio' tool was not found"
}

function unpack_rpm() {
    # Auto-detect whatever the RPM is compressed
    INFO "Unpacking $1.."

    tmpfile="/tmp/.tmpfile.$$"
    rpm2cpio $1 > $tmpfile || ABORT "rpm2cpio $1 has failed with $?"
    if [[ `file $tmpfile` =~ "ASCII cpio archive" ]] ; then
        # Not compressed
        INFO "not compessed"
        cpio -idmu <$tmpfile 
    else
        # Compressed RPM
#        (lzma d -so $tmpfile | cpio -idmu)
        (xz -dc $tmpfile | cpio -idmu)
    fi
    [ $? -eq 0 ] || ABORT "Installing $1 has failed"

    # Extract RPM installation scripts
    rpm -qp $1 --scripts > $1.scripts

    rm -f $tmpfile
    return 0
}

##########
## MAIN ##

[[ "$*"x != ""x ]] || ABORT "Usage: $0 <rpms list>"

echo "Checking environemnt for required tools.."
check_environment

echo "Going to unpack $@ to ./root/ folder and save RPM scripts to {$@}.scripts file(s)"

[[ ! -n "$DEBUG" ]] || set -x

mkdir -p root
cd root
for f in "$@" ; do unpack_rpm ../$f ; done
